import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import BootstrapClient from "@/components/BootstrapClient";
import { Toaster } from "react-hot-toast";
import { AuthContextProvider } from "@/context/AuthContext/AuthContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Clasp Finance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthContextProvider>
      <html lang="en">
        <body className={inter.className}>
          {children} <BootstrapClient />
          <Toaster />
        </body>
      </html>
    </AuthContextProvider>
  );
}
